name = "Tiberius"
license = "Apache-2.0"
licenselink = "https://github.com/nicholasnooney-com/tiberius/blob/main/LICENSE"
description = "The second Hugo Theme for nicholasnooney.com"
homepage = "https://github.com/nicholasnooney-com/tiberius"
tags = []
features = []
min_version = "0.41.0"

disableKinds = ["page", "section", "taxonomy", "term"]

[author]
  name = "Nicholas Nooney"
  homepage = "https://nicholasnooney.com"

[module]
  # Folders in this repo that should be mounted to Hugo's Virtual Filesystem.
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"

  # Dependencies that should be mounted to Hugo's Virtual Filesystem.
  [[module.imports]]
    path = "github.com/nicholasnooney-com/hugolibs/feather-icons"
    [[module.imports.mounts]]
      source = "dist"
      target = "assets/js/modules/feather-icons"
  [[module.imports]]
    path = "github.com/nicholasnooney-com/hugolibs/lunr"
    [[module.imports.mounts]]
      source = "."
      target = "assets/js/modules/lunr"
